a = (5)
b = (2)
print("la primera variable es:",(a))
print("el signo de operacion es: +")
print("la segunda variable es", (b))
c = (a+b)
a = (3)
b = (4)
print("el resultado es: ", (c))
print(type (c))
print("la primera variable es:",(a))
print("el signo de operacion es: -")
print("la segunda variable es", (b))
c = (a-b)
a = (8)
b = (6)
print("el resultado es: ", (c))
print(type (c))
print("la primera variable es:",(a))
print("el signo de operacion es: *")
print("la segunda variable es", (b))
c = (a*b)
a = (4)
b = (6)
print("el resultado es: ", (c))
print(type (c))
print("la primera variable es:",(a))
print("el signo de operacion es: /")
print("la segunda variable es", (b))
c = (a/b)
a = (15)
b = (3)
print("el resultado es: ", (c))
print(type (c))
print("la primera variable es:",(a))
print("el signo de operacion es: **")
print("la segunda variable es", (b))
c = (a**b)
a = (236)
b = (22)
print("el resultado es: ", (c))
print(type (c))
print("la primera variable es:",(a))
print("el signo de operacion es: %")
print("la segunda variable es", (b))
c = (a%b)
a = (21)
b = (4)
print("el resultado es: ", (c))
print(type (c))

a = int (input ("ingrese valor"))
b = int (input ("ingrese valor"))
res = a+b
print ("la suma de los numeros es: ", res)
res = a-b
print ("la resta de los numeros es: ", res)
res = a*b
print ("la multiplicacion de los numeros es: ", res)